require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'wittyclip' do

  pod 'react-native-ffmpeg/full-gpl', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNReactNativeGetMusicFiles', :path => '../node_modules/react-native-get-music-files'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNVideoEditor', :path => '../node_modules/react-native-video-editor'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"


  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'wittyclipTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'wittyclip-tvOS' do
  # Pods for wittyclip-tvOS

  target 'wittyclip-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
